version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-ganaderia
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tienda
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ganaderia-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uuser", "-ppassword"]
      interval: 5s
      timeout: 3s
      retries: 10

  nest-app:
    build: 
      context: backend
      dockerfile: Dockerfile
    container_name: nest-ganaderia
    ports:
      - '5000:5000'
    env_file:
      - /backend/.env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ganaderia-net

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: react-ganaderia
    ports:
      - '3000:80'
    networks:
      - ganaderia-net
    depends_on:
      - nest-app

volumes:
  mysql-data:

networks:
  ganaderia-net: